baseURL = "https://dadrian.io"
defaultContentLanguage = "en-us"
languageCode = "en"
locale = "en-us"
title = "David Adrian"
theme = ["dadrian"]
[pagination]
pagerSize = 100
[markup]
  [markup.highlight]
    tabWidth = 4
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
[params]
  images = [ "img/david4.jpg" ]
[security]
  allowContent = ["^text/markdown$", "^text/html$"]
