baseURL = "https://dadrian.io"
languageCode = "en-us"
title = "David Adrian"
theme = ["dadrian"]
[pagination]
pagerSize = 100
[markup]
  [markup.highlight]
    tabWidth = 4
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
  images = [ "img/david4.jpg" ]
