[context.production.environment]
HUGO_VERSION = "0.53"
HUGO_BASEURL = "https://dadrian.io"

[context.deploy-preview]
command = "hugo  --gc --minify --buildFuture --buildDrafts -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo  --gc --minify --buildFuture --buildDrafts -b $DEPLOY_PRIME_URL"
