[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_BASEURL = "https://dadrian.io"

[context.deploy-preview]
HUGO_VERSION = "0.74.3"
command = "hugo  --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
HUGO_VERSION = "0.74.3"
command = "hugo  --gc --minify --buildFuture --buildDrafts -b $DEPLOY_PRIME_URL"
