name = "dadrian-io"
pages_build_output_dir = "./public"

[build]
command = "hugo --gc --minify"

[env.preview]
build.command = "hugo --gc --minify --buildFuture --buildDrafts -b ${CF_PAGES_URL}"

[env.production.vars]
HUGO_BASEURL = "https://dadrian.io"
